projects:
  safteyapp:
    schemaPath: app/src/main/graphql/schema.json
    includes:
      - app/src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app/src/main/graphql/com/amazonaws/amplify/generated/graphql
        graphQLApiId: zni2tghz7nevdodc4r4xwzbdf4
      endpoints:
        prod: >-
          https://taxffomadbfnbccnsjnfjdkqoa.appsync-api.us-west-2.amazonaws.com/graphql
